### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ArseniySavin** [Serg046/MsBuildTaskExplorer#23]
Please add me into contributors please. And you create the dev branch. I want add feature in extension.

**Comment by ArseniySavin** [comment]
I am create builds file for release management. I am naming file as .target, .property, .task. This is extension useful. And I extend it add custom features for adding extension into setting.

My view build folder

Solution folder
 |_BuildAndPublish.target
 |_build
 |    |_Env.property
 |    |_Env.task
 |_src
 |.....

**Comment by Serg046** [comment]
Done, now you are in collaborators list. But please do not commit into master directly. Please create a separate branch for your feature and then create PR because I would like to control master.

**Comment by ArseniySavin** [comment]
ОК.
