### ISSUE TITLE
Styling issue with Dark Theme (Visual Studio 2019)

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#31]
Hello,

Please refer to https://github.com/Serg046/MsBuildTaskExplorer/issues/30 for additional context.

In Visual Studio 2019, when using the Dark Theme, the styling of MSBuild Task Explorer has at east one issue: the font color of the textbox is almost the same as the background color, which makes the text hard to read. Since I am unable to use MSBuild Task Explorer further, there might be other issues I am unable to identify at the moment (see https://github.com/Serg046/MsBuildTaskExplorer/issues/30).

![MSBuild-Task-Explorer_No-Target-And-Filter-Not-Working-And-Style-Issue](https://user-images.githubusercontent.com/3876562/74273460-cb122180-4d10-11ea-8dac-2f6a1eb47625.png)

**Comment by Serg046** [comment]
This is what I see on my VS. Could you clarify which color theme, VS version and Windows version do you use?

![image](https://user-images.githubusercontent.com/4963385/74450907-7513ba00-4e87-11ea-8baa-257bfcf0e817.png)

**Comment by alexis-** [comment]
**Visual Studio version**: 16.4.3
**OS**: Windows 7 SP1 with latest updates
**Theme**: Dark

Let me know if you need anything else. I will also check on my desktop computer which is running Windows 10.

**Comment by Serg046** [comment]
Yes, please. Let's wait until you try on win10 to be sure the issue is not related to the version of Windows.

**Comment by alexis-** [comment]
Hello Serg,

Everything appears to be fine on my desktop.
- latest VS 2019 Enterprise,
- latest Win10 update,
- Dark theme

![image](https://user-images.githubusercontent.com/3876562/74537790-114ac900-4f3b-11ea-98c5-37d7b131929f.png)

**Comment by Serg046** [comment]
Shoud be fixed by `v1.5`, please confirm

**Comment by alexis-** [comment]
I confirm this is working. Fantastic work, thank you !
