### ISSUE TITLE
Project name filtering ineffective (Visual Studio 2019) 

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#32]
Hello,

Please refer to #30 for additional context.

In Visual Studio 2019, filtering by project name seem to be completely ineffective (nothing happens).

![MSBuild-Task-Explorer_No-Target-And-Filter-Not-Working-And-Style-Issue](https://user-images.githubusercontent.com/3876562/74273708-2cd28b80-4d11-11ea-8a6f-e4f1a8acc7bc.png)

**Comment by Serg046** [comment]
The search is designed for targets only. How do you see this feature? The only thing I could suggest is regex support. Something like `SuperMemo.*TargetName`

**Comment by alexis-** [comment]
This isn't that big a deal for me. It would be nice not to need scrolling, but I think your time will be best used for something else.

Your solution would be very acceptable if you choose to implement it.
