### ISSUE TITLE
Allow matching partial content in search filter ("Contains" instead of "StartsWith")

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#35]
The new project search filtering only works if you type the exact path to your project. Would it be possible to find matches that **contains** the term instead ?

**Comment by Serg046** [comment]
It works based on Regex expressions, so it should be available. E.g. `AppHost|Clean` or `AppHost|` or even `Ap.+Host|` work for me. Is this what you were looking for?

**Comment by Serg046** [comment]
The current search works based on the targets if you don't have the delimiter sign `|`. But I changed it there 3bda872f9cd3c986c641dd3da443d85554612ba6. So that you will be able to use just `AppHost` instead of `AppHost|` from the example above.

**Comment by alexis-** [comment]
Okay, makes sense. Let me know when it's out and I'll test it.

**Comment by Serg046** [comment]
Released

**Comment by alexis-** [comment]
Works great, thanks.
