### ISSUE TITLE
MSBuildTaskExplorer stops working properly after reloading a project 

### ISSUE THREAD

**Issue by alexis-** [Serg046/MsBuildTaskExplorer#39]
As the title states, MSBuildTaskExplorer stops working properly after reloading a project:

Projects and Targets are still displayed correctly, but their respective buttons (Run and Print variables) stop functioning (clicking them doesn't produce any result).

**Comment by Serg046** [comment]
Depends on https://github.com/Serg046/EventBinder/issues/13

**Comment by Serg046** [comment]
Fixed, should work even if the project is unloaded
