### ISSUE TITLE
Wrong tasks shown after switching solution

### ISSUE THREAD

**Issue by x3ntrix** [Serg046/MsBuildTaskExplorer#41]
When we switch the solution the MSBuild task explorer shows the targets from the previous solution. Interesting is that is does not show all targets. Targets from files in sub-directories disappear. Only the targets from files in the root directory where the solution file is remain.

**Comment by Serg046** [comment]
v1.7.1 should fix that

**Comment by x3ntrix** [comment]
It works now. Thx.
