### ISSUE TITLE
Integrate into Task Runner Explorer

### ISSUE THREAD

**Issue by xperiandri** [Serg046/MsBuildTaskExplorer#94]
It would be nice to integrate this functionality as Task Runner into Visual Studio Task Runner Explorer tool window.
Like it worked for ASP.NET Core 1.0 preview 7 some time earlier https://github.com/madskristensen/ProjectTaskRunner

**Comment by xperiandri** [comment]
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TaskRunnerProjectTemplate

**Comment by Serg046** [comment]
There was such a request already https://github.com/Serg046/MsBuildTaskExplorer/issues/21. Tbh, this is not what I want to do because I'd control UI. Maybe this is a better fit for https://github.com/samartzidis/MSBuildTargetsVsExtension.
